# POSTTEST 7: Tensorflow Basics
### NIM: 2009106072
### Nama: Gilang Raditya

In [1]:
import tensorflow as tf

#### Membuat tensor dengan shape [5,5] berisi nilai random yang disimpan di random_tensor

In [2]:
random_tensor = tf.random.normal((5,5))
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.22622663, -0.36066198,  1.175426  ,  0.64252436,  0.1574099 ],
       [ 1.5613352 ,  1.7785823 , -0.17681094,  0.43336314, -0.6585206 ],
       [ 0.33694857, -1.7237477 ,  0.08569267,  0.00848309, -2.1404247 ],
       [-0.04138266,  0.22151248, -0.7253971 ,  0.7001921 ,  0.04732831],
       [-0.68235445,  0.19296111,  0.21254778,  0.8092129 , -0.69797564]],
      dtype=float32)>

#### Membuat tensor dengan shape [5,5] berisi bilangan prima yang disimpan di prime_tensor

In [3]:
prime_list = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
prime_tensor = tf.constant(prime_list, shape=(5,5), dtype=tf.float32)

#### Menampilkan dimensi dari kedua variable tersebut

In [4]:
print(f"Bentuk Random Tensor : {random_tensor.shape.as_list()}",
      f"Bentuk Prime Tensor : {prime_tensor.shape.as_list()}", sep="\n")

Bentuk Random Tensor : [5, 5]
Bentuk Prime Tensor : [5, 5]


#### Melakukan min.5 Operasi aritmatika pada 2 variable tersebut

Operasi penjumlahan

In [5]:
tf.add(prime_tensor, random_tensor).numpy()

array([[ 1.7737734,  2.639338 ,  6.175426 ,  7.6425242, 11.15741  ],
       [14.561336 , 18.778582 , 18.823189 , 23.433363 , 28.34148  ],
       [31.336948 , 35.276253 , 41.085693 , 43.008484 , 44.859573 ],
       [52.95862  , 59.22151  , 60.274605 , 67.700195 , 71.047325 ],
       [72.31764  , 79.19296  , 83.21255  , 89.80921  , 96.302025 ]],
      dtype=float32)

Operasi Pengurangan

In [6]:
tf.subtract(prime_tensor, random_tensor).numpy()

array([[ 2.2262266,  3.360662 ,  3.824574 ,  6.3574758, 10.84259  ],
       [11.438664 , 15.221417 , 19.176811 , 22.566637 , 29.65852  ],
       [30.663052 , 38.723747 , 40.914307 , 42.991516 , 49.140427 ],
       [53.04138  , 58.77849  , 61.725395 , 66.299805 , 70.952675 ],
       [73.68236  , 78.80704  , 82.78745  , 88.19079  , 97.697975 ]],
      dtype=float32)

Operasi Perkalian

In [7]:
tf.multiply(prime_tensor, random_tensor).numpy()

array([[  -0.45245326,   -1.081986  ,    5.87713   ,    4.4976707 ,
           1.731509  ],
       [  20.297358  ,   30.235899  ,   -3.3594077 ,    9.967352  ,
         -19.097097  ],
       [  10.445406  ,  -63.778667  ,    3.5133994 ,    0.36477274,
        -100.59996   ],
       [  -2.1932807 ,   13.069237  ,  -44.24922   ,   46.91287   ,
           3.3603098 ],
       [ -49.811874  ,   15.243928  ,   17.641466  ,   72.01995   ,
         -67.703636  ]], dtype=float32)

Operasi Pembagian

In [8]:
tf.divide(prime_tensor, random_tensor).numpy()

array([[-8.8406925e+00, -8.3180380e+00,  4.2537770e+00,  1.0894528e+01,
         6.9881241e+01],
       [ 8.3262072e+00,  9.5581741e+00, -1.0745942e+02,  5.3073273e+01,
        -4.4038109e+01],
       [ 9.2002167e+01, -2.1464857e+01,  4.7845401e+02,  5.0689097e+03,
        -2.1958260e+01],
       [-1.2807299e+03,  2.6635068e+02, -8.4091873e+01,  9.5688026e+01,
         1.5001593e+03],
       [-1.0698252e+02,  4.0940891e+02,  3.9050043e+02,  1.0998341e+02,
        -1.3897333e+02]], dtype=float32)

Operasi Pemangkatan

In [9]:
tf.pow(prime_tensor, random_tensor).numpy()

array([[8.5486788e-01, 6.7285347e-01, 6.6311297e+00, 3.4913716e+00,
        1.4585642e+00],
       [5.4857876e+01, 1.5433154e+02, 5.9415859e-01, 3.8915503e+00,
        1.0888820e-01],
       [3.1806231e+00, 1.9806870e-03, 1.3746867e+00, 1.0324211e+00,
        2.6363338e-04],
       [8.4848642e-01, 2.4675493e+00, 5.0690539e-02, 1.8993418e+01,
        1.2235365e+00],
       [5.3524591e-02, 2.3236368e+00, 2.5579720e+00, 3.7798241e+01,
        4.1047029e-02]], dtype=float32)

Operasi Perkalian Matriks

In [10]:
tf.matmul(prime_tensor, random_tensor).numpy()

array([[  -1.8792825 ,   -0.3311569 ,   -0.49087167,   16.43024   ,
         -19.7093    ],
       [   9.263695  ,    3.486745  ,    3.382666  ,   55.452763  ,
         -68.96934   ],
       [  30.721153  ,    2.547581  ,   12.207272  ,  104.441765  ,
        -138.01271   ],
       [  49.462822  ,    9.214239  ,   23.582268  ,  164.50667   ,
        -207.46118   ],
       [  64.92622   ,    9.54047   ,   35.007317  ,  222.65482   ,
        -281.6789    ]], dtype=float32)

Operasi dot product

In [11]:
tf.tensordot(prime_tensor, random_tensor, axes=0).numpy()

array([[[[-4.52453256e-01, -7.21323967e-01,  2.35085201e+00,
           1.28504872e+00,  3.14819813e-01],
         [ 3.12267041e+00,  3.55716467e+00, -3.53621870e-01,
           8.66726279e-01, -1.31704116e+00],
         [ 6.73897147e-01, -3.44749546e+00,  1.71385333e-01,
           1.69661734e-02, -4.28084946e+00],
         [-8.27653110e-02,  4.43024963e-01, -1.45079422e+00,
           1.40038419e+00,  9.46566164e-02],
         [-1.36470890e+00,  3.85922223e-01,  4.25095558e-01,
           1.61842585e+00, -1.39595127e+00]],

        [[-6.78679883e-01, -1.08198595e+00,  3.52627802e+00,
           1.92757308e+00,  4.72229719e-01],
         [ 4.68400574e+00,  5.33574677e+00, -5.30432820e-01,
           1.30008936e+00, -1.97556174e+00],
         [ 1.01084566e+00, -5.17124319e+00,  2.57077992e-01,
           2.54492611e-02, -6.42127419e+00],
         [-1.24147967e-01,  6.64537430e-01, -2.17619133e+00,
           2.10057640e+00,  1.41984925e-01],
         [-2.04706335e+00,  5.78883350e-01, 

#### Menampilkan nilai maksimal dan minimum dari variable random tensor

Mengambil index nilai maksimum berdasarkan kolom

In [12]:
tf.argmax(random_tensor, axis=0).numpy()

array([1, 1, 0, 4, 0], dtype=int64)

Mengambil index nilai minimum berdasarkan kolom

In [22]:
tf.argmin(random_tensor, axis=0).numpy()

array([4, 2, 3, 2, 2], dtype=int64)

Mengambil nilai maksimum berdasarkan kolom

In [14]:
max_col = tf.reduce_max(random_tensor, axis=0)
max_col.numpy()

array([1.5613352, 1.7785823, 1.175426 , 0.8092129, 0.1574099],
      dtype=float32)

Mengambil nilai minimum berdasarkan kolom

In [15]:
min_col = tf.reduce_min(random_tensor, axis=0)
min_col.numpy()

array([-0.68235445, -1.7237477 , -0.7253971 ,  0.00848309, -2.1404247 ],
      dtype=float32)

Menampilkan nilai maximum random_tensor

In [16]:
tf.reduce_max(max_col).numpy()

1.7785823

Menampilkan nilai minimum random_tensor

In [17]:
tf.reduce_min(min_col).numpy()

-2.1404247

#### Menampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [18]:
tf.concat([random_tensor, prime_tensor], axis=0).numpy()

array([[-2.2622663e-01, -3.6066198e-01,  1.1754260e+00,  6.4252436e-01,
         1.5740991e-01],
       [ 1.5613352e+00,  1.7785823e+00, -1.7681094e-01,  4.3336314e-01,
        -6.5852058e-01],
       [ 3.3694857e-01, -1.7237477e+00,  8.5692666e-02,  8.4830867e-03,
        -2.1404247e+00],
       [-4.1382656e-02,  2.2151248e-01, -7.2539711e-01,  7.0019209e-01,
         4.7328308e-02],
       [-6.8235445e-01,  1.9296111e-01,  2.1254778e-01,  8.0921292e-01,
        -6.9797564e-01],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01]], dtype=float32)

#### Tampilkan hasil sorting dari kedua variable di atas. (descending)

Menampilkan hasil sorting random_tensor secara descending

In [19]:
tf.sort(random_tensor, direction='DESCENDING').numpy()

array([[ 1.175426  ,  0.64252436,  0.1574099 , -0.22622663, -0.36066198],
       [ 1.7785823 ,  1.5613352 ,  0.43336314, -0.17681094, -0.6585206 ],
       [ 0.33694857,  0.08569267,  0.00848309, -1.7237477 , -2.1404247 ],
       [ 0.7001921 ,  0.22151248,  0.04732831, -0.04138266, -0.7253971 ],
       [ 0.8092129 ,  0.21254778,  0.19296111, -0.68235445, -0.69797564]],
      dtype=float32)

Menampilkan hasil sorting prime_tensor secara descending

In [20]:
tf.sort(prime_tensor, direction='DESCENDING').numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)